#!/bin/bash


if [ "$1" == "" ]; then
	echo "specify one or more pdf files ( output will out.pdf )"
	exit 1
fi

gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/ebook \
	-sOutputFile=out.pdf \
	$*
