#!/bin/bash

if [ "$2" == "" ]; then
	echo "$0 registry-host image [user] [pass]"
	exit 0
fi

user="$3"
pass=""

if [ "$3" != "" ]; then
	if [ "$4" != "" ]; then
		pass=$4
	else
		read -sp "Password: " pass
	fi
fi

if [ "$user" == "" ]; then
	curl -s https://$1/v2/$2/tags/list
else
	curl -s https://$1/v2/$2/tags/list --user $user:$pass
fi
