#!/bin/bash

if [ "$1" == "" ]; then
	echo "$0 registry-host [user] [pass]"
	exit 0
fi

user="$2"
pass=""

if [ "$2" != "" ]; then
	if [ "$3" != "" ]; then
		pass=$3
	else
		read -sp "Password: " pass
	fi
fi

echo
if [ "$user" == "" ]; then
	curl -s https://$1/v2/_catalog
else
	curl -s https://$1/v2/_catalog --user $user:$pass
fi
