#!/bin/bash

#set -x

if [ "$3" == "" ]; then
	echo "$0 registry-host image user [pass]"
	exit 0
fi

pass=""

if [ "$4" != "" ]; then
	pass=$4
else
	read -sp "Password: " pass
fi

curl https://$1/v2/$2/tags/list --user $3:$pass
