#!/bin/bash

# dk-rm-if-exists <container> [-y]

stop_and_remove()
{
	echo -n '---> stopping...'
	docker stop $1
	echo -n '---> removing...'
	docker rm $1
}

docker inspect $1 >&/dev/null
if [ $? == "0" ]; then
	if [ "$2" == "-y" ]; then
		stop_and_remove $1
	else
	        read -p "container [$1] already exists, want to stop and remove ? " -n 1 -r
	        echo
	        if [[ $REPLY =~ ^[Yy]$ ]]; then stop_and_remove $1; else exit 1; fi
	fi
fi

