#!/bin/bash

which dotnet>/dev/null

if [ "$?" != "0" ]; then
    echo "missing dotnet"
    exit 0
fi

if [ "$1" == "" ]; then
    echo "specify tool name for which to retrieve version"
    exit 0
fi

dotnet tool list -g | grep "$1 " | awk '{print $2}'