#!/bin/bash

if [ "$1" == "" ]; then
	echo "specify jwt token"
	exit 0
fi

hdr="$(echo "$1" | jq -R 'split(".") | .[0] | @base64d | fromjson')"
payload="$(echo "$1" | jq -R 'split(".") | .[1] | @base64d | fromjson')"

nbf="$(echo $payload | jq '.nbf' | jq 'todate')"
exp="$(echo $payload | jq '.exp' | jq 'todate')"
iat="$(echo $payload | jq '.iat' | jq 'todate')"

echo $hdr | jq
echo $payload | jq ".nbf=$nbf" | jq ".exp=$exp" | jq ".iat=$iat"
