#!/bin/bash

#set -x

which shu>/dev/null

if [ "$?" != "0" ]; then
    echo "shu requirement missing, install with:"
    echo "dotnet tool install --global shu --version 0.0.4"
    exit 0
fi

which markdown-toc>/dev/null

if [ "$?" != "0" ]; then
    echo "markdown-toc requirement missing, install with"
    echo "npm install -g markdown-toc"
    exit 0
fi

mdtoken='<!-- TOC -->'
mdtokenEnd='<!-- TOCEND -->'

if [ "$1" == "" ]; then
    echo "Generate toc unshift by 1 level:"
    echo "$0 [file]"
    echo
    echo "Generate toc preserving all levels:"
    echo "MTOCPRESERVE=1 $0 [file]"
    echo
    echo "Specify markdown file to create toc"
    echo "file must contains follow token where toc placed"
    echo
    echo $mdtoken
    echo 'any text'
    echo $mdtokenEnd
    exit 0
fi

which uuid >/dev/null

if [ "$?" != "0" ]; then
    echo "uuid command missing"
    exit 0
fi

if [ "$MTOCPRESERVE" == "1" ]; then
    s=$(markdown-toc "$1")
else
    s=$(markdown-toc "$1" | \
        sed -r '/^- .*/d' | \
        sed 's/^  //g' \
        )
fi

tmpfile="$1".$(uuid)

cat "$1" | \
    shu replace-token -csregex "$mdtoken"".*""$mdtokenEnd" "$mdtoken""$mdtokenEnd" | \
    shu replace-token "$mdtoken" "$mdtoken\n""$s\n" > "$tmpfile"

mv -f "$tmpfile" "$1"
