#!/bin/bash

# args
#-------
# $1- scale input (1.0)
# $2- columns count
# $3- rows count
# $4- cnt
# $5- input file
#

if [ "$5" == "" ]; then
    echo "specify SCALE COLS ROWS CNT INPUTPDF"
    echo "example: $0 1.0 1 5 4 ./file.pdf to apply 4 times the file.pdf in a grid 1col 5rows"
    echo "output will written to out.pdf"
    exit 0
fi

nfo="$(pdfinfo "$5" | grep "Page size:")"

if [ "$nfo" == "" ]; then
    echo "error: unable to retrieve pdf file info; verify pdfinfo tool installed."
    exit 1
fi

chk="$(echo $nfo | grep pts)"
if [ "$chk" == "" ]; then
    echo "error: pdfinfo retrieve size not in pts"
    exit 2
fi

w="$(echo $nfo | awk '{print $3}')"
h="$(echo $nfo | awk '{print $5}')"

echo "$5 size is $w x $h"

echo "TIP: A4 could contains cols=$(echo "595.276 / $w" | bc -l) rows=$(echo "841.89 / $h" | bc -l)"

nw="$(echo "$w * $1 * $2" | bc)"
nh="$(echo "$h * $1 * $3" | bc)"

echo "nup size will be $nw x $nh"

files=""

let cnt=0
let i=0
while (( $i < $4 )); do
    if [ "$i" == "0" ]; then
        files="$5"
    else
        files="$files $5"
    fi  
    let i=$i+1     
done

echo "$i files to a single page"

pdfjam --papersize "{${nw}pt,${nh}pt}" --nup $2x$3 --outfile out.pdf $files