#!/bin/bash

if [ "$1" == "" ]; then

    echo "specify a systemd env file to source"
    echo "example: source source-system-env FILE.env"
    exit 1

fi

for line in `cat $1`; do

    if [[ $line =~ ([^=]*)=(.*) ]]; then

        varname="${BASH_REMATCH[1]}"
        varvalue="${BASH_REMATCH[2]}"

        if [[ $varvalue =~ \"(.*)\" ]]; then

            varvalue="${BASH_REMATCH[1]}"

        fi

	    # echo "match $varname=$varvalue"

        export $varname=$varvalue
    fi

done
