#!/usr/bin/env bash

# ref: https://github.com/devel0/knowledge/blob/8aed669981349d276fb23a0d2771893138869c44/doc/prompt-colors.md

themeprompt() {    

    fg=""
    bg=""

    case $1 in

    prod)
        fg=15
        bg=160
        ;;

    prod-user)
        fg=160
        ;;

    dev)
        fg=15
        bg=226
        ;;

    dev-user)
        fg=226
        ;;

    test)
        fg=15
        bg=22
        ;;

    test-user)
        fg=22
        ;;

    --help)
        echo "specify one of follow profiles: prod prod-user dev dev-user test test-user"
        return
        ;;    

    esac

    if [ "$fg" == "" ] && [ "$1" != "" ] && (( $1 )); then
        fg=$1
    fi

    if [ "$bg" == "" ] && [ "$2" != "" ] && (( $2 )); then
        bg=$2
    fi

    # echo "using fg=$fg bg=$bg"

    DEFAULT_PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'

    if [ "$fg" != "" ] && [ "$bg" != "" ]; then
        PS1="$(echo $DEFAULT_PS1 | sed 's/01;32/1;38;5;${fg};48;5;${bg}/') "
    elif [ "$fg" != "" ]; then
        PS1="$(echo $DEFAULT_PS1 | sed 's/01;32/1;38;5;${fg}/') "
    else
        PS1=$DEFAULT_PS1
    fi    

}
